### ISSUE TITLE
Incorrect deserialization of dataclasses with similar fields

### ISSUE THREAD

**Issue by davidjson9** [yukinarit/pyserde#142]
Here is an example where I have two very similar classes, Alpha and Bravo. Alpha has an additional optional field. I serialize Bravo, and when I deserialize I get back Alpha.

```python
from dataclasses import dataclass
from typing import Union, Optional

from serde import deserialize, serialize
from serde.json import from_json, to_json


@deserialize
@serialize
@dataclass
class Alpha:
    a: str
    b: Optional[str]

@deserialize
@serialize
@dataclass
class Bravo:
    a: str

@deserialize
@serialize
@dataclass
class Foo:
    d: Union[Alpha, Bravo]


def main():
    f = Foo(Bravo(a=1))

    # convert into json
    Bravo_json = to_json(f)
    print(f"Into Json: {Bravo_json}")

    # convert back
    print(f"From Json: {from_json(Foo, Bravo_json)}")


if __name__ == '__main__':
    main()
```

Output:
```
Into Json: {"d": {"a": 1}}
From Json: Foo(d=Alpha(a=1, b=None))
```

**Comment by yukinarit** [comment]
Hi @davidjson9  

This is actually the limitation of the current pyserde, because deserialization from `{"a": 1}`  goes successfully for both `Alpha` and `Bravo`.

In order to fix pyserde working properly for this case, we need to introduce the concept of `External Tagging` which is described in Rust serde's [documentation](https://serde.rs/enum-representations.html). pyserde's enum representation is `Internal Tagging`.

I will take a look after [flatten](https://github.com/yukinarit/pyserde/pull/140) feature 👍
