### ISSUE TITLE
Custom class serializer doesn't work for nested data?

### ISSUE THREAD

**Issue by AustinScola** [yukinarit/pyserde#261]
Hey @yukinarit,

I'm running into an issue with a custom class level serializer. I have a `dataclass` with a field that is a dictionary and I want all `datetime`s in the dict to be serialized using `.timestamp()`. This seems to work for top level values, but not for anything nested ? I'm not sure exactly what the expected behavior is here? Is there a different way to accomplish this or is it a bug?

Example
```python
from dataclasses import dataclass
from datetime import datetime
from typing import Any

from serde import SerdeSkip, serde
from serde.json import to_json


def serializer(cls, o):
    if cls is datetime or isinstance(o, datetime):
        return o.timestamp()
    else:
        raise SerdeSkip()


@serde(serializer=serializer)
@dataclass
class Foo:
    bar: dict[str, Any]


def main():
    d = datetime(2021, 1, 1, 0, 0, 0)
    foo = Foo(bar={"d": d})
    print(to_json(foo))  # prints {"bar":{"d":1609477200.0}}

    # The nested datetime here isn't serialized as I would expect it to be?
    d = datetime(2021, 1, 1, 0, 0, 0)
    foo = Foo(bar={"a": {"d": d}})
    print(to_json(foo))  # prints {"bar":{"a":{"d":"2021-01-01T00:00:00"}}}



if __name__ == '__main__':
    main()
```

**Comment by yukinarit** [comment]
Hi @AustinScola  

pyserde doesn't inspect the nested type at Runtime if the type is declared as `Any`.  That is because of the performance.
The library like [dataclasses-json](https://github.com/lidatong/dataclasses-json) does runtime type inspection therefore it was said to be really slow.

---
I wanted to provide this code as a workaround 

```python
@serde(serializer=serializer)
@dataclass
class Foo:
    bar: dict[str, Union[datetime, dict[str, datetime]]]
```

But it seems custom serializer isn't supported for Union yet 😄 
Let me check if I can quickly implement it.

**Comment by yukinarit** [comment]
Please use new class (de)serializer.
https://yukinarit.github.io/pyserde/guide/en/class-attributes.html#class_serializer--class_deserializer
