### ISSUE TITLE
Switch from flake8 to pycodestyle?

### ISSUE THREAD

**Issue by yukinarit** [yukinarit/pyserde#59]
I don't know how to fix `E741 ambiguous variable name 'I'`... 

```
$ pipenv run flake8
./tests/data.py:220:5: E741 ambiguous variable name 'I'
./build/lib/serde/inspect.py:19:1: F401 '.core.logger' imported but unused
make: *** [pep8] Error 1
```

**Comment by alexmisk** [comment]
According to [E471](https://www.flake8rules.com/rules/E741.html):

*"Variables named I, O, and l can be very hard to read. This is because the letter I and the letter l are easily confused, and the letter O and the number 0 can be easily confused. Change the names of these variables to something more descriptive."*

All you need is to rename confusing variables (e.g. "I" → "int_value" or similar).
